### PR TITLE
inline `isString` `isFunction` `isNumber`

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM, sorry for letting this sit. Lets get a rebase, then we can merge.

**Comment by bekzod** [comment]
needs restart I think

**Comment by bekzod** [comment]
ping :P

**Comment by stefanpenner** [comment]
needs rebase, post the Typings/style PR i just merged.

**Comment by bekzod** [comment]
done

**Pull request merged**
