### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by stefanpenner**
- [ ] split into separate PR
---

- [X] micro-task for auto-runs (would be nice to factor to share \w RSVP?)
- [X] add note to where to deprecate nested runs
- [X] incremental Queue flush
- [ ] Incremental flush across different mechanisms for a subset of queues (rAF/ micro-task), ala igniter

### CODE REVIEW

**Comment by stefanpenner** [comment]
Interesting popup blocker details:

|   | sync | micro task |  raf |  setTimeout |
|---|---|---|---|---|
|Chrome 55|✓|✓|blocker|✓|
|Safari 9.1.2 | ✓ |nothing|nothing | ✓ |
|FF 50|✓|blocker|blocker|✓|

**Comment by kanongil** [comment]
I was just debugging a sub 60-fps rendering issue, where I saw that the `setTimeout(x, 0)` delay can push my event callback `deferOnce()` logic past the start of the next frame, causing a frame drop.

I was about to suggest a micro-task approach instead, but it seems that you are already on this. 👍

**Comment by stefanpenner** [comment]
@kanongil so, if you are hitting `setTimeout` because of BB. It is most likely the result of something not being correctly wrapped in the run-loop. Although ^ will help quite a-bit, being able to perform work synchronously in the current task will tend to out-perform even micro-task. (There are some quirks with GC/JIT where they may not be true, but generally...)

**Comment by kanongil** [comment]
@stefanpenner Ah, I had always assumed that Embers `Ember.run.schedule()`, etc created a run loop when needed (which it does, just not immediately). Thanks for the clarification.

Anyway, this still look interesting :-)

**Comment by stefanpenner** [comment]
@kanongil well, it will create a new one (with an autorun) if not already in one.

**Comment by stefanpenner** [comment]
plumbing for incremental stuff landed, and micro-task for auto-run is landing here: https://github.com/BackburnerJS/backburner.js/pull/306

**Pull request closed without merging**
